travis:
  secure:
    BINSTAR_TOKEN: bO0IaKGMHVv+2ZAIG8qN4v1vSAp9Ob3lrnGqXjNnAhDTZrONiZsty5h0uzHPD6k5OTmHdkP0unlXjMNt1IkzQAj3AVVFeQmJQFfpwR4iCp5NLl/unbMw82O3P+xUd3A59MSN1qIKQH+MKRVP69cRSUjhpf70c/kC8c5/rFFuQcUtEi7HsNq/FWNIwzM16onYrIEk4NezhVClBs+p1p7ExggWziVjc43T87b73KCoo0+RV3CkIdY9UWde19i/cFhKBHwsxDBvdwazWYZF/CKisYPhzInsuPtC4sTr73x8u5CDMaIeD2R0BCkVCO5JsOQxR64igm0uKH6qa5vXUiQWtkO84O5KVZsFMrkP+hVR8wWN1BNYGD8EYKlrem2z1c/4TyaxahkMbgmACtdvOsAchq60qB49G1URN7D0mlhoxUlo5ha4E/+NetzKL+uNmdEINVPQJaKxPWorZL+7ymd8ew57XEtN4/o9kIvZ4UILXTg9LCqFy2+egGHPbdKW9zwZOt5Kgo4hLKjHBKqQh+fcbzYlVqaUx1ig8JTCZE7iLn73lVYBT2qfV5HFHJsOvA3TT3XKYEVPXUXoIOx4ywONVV2lSxdLgNcGYUySkAbc2CG2X6R0ormw7qtgnaS8CQwoJjnfBWXXDdimggevV0n5MbdoMKfLbxwAJw973iRbCZM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
